Description:  This template deploys an internet gateway, and a pair of NAT gateways (one in each AZ)

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String

  VPC:
    Description: Please enter the ID for this VPC
    Type: String

  PublicSubnet1:
    Description: A reference to the public subnet in the 1st Availability Zone
    Type: String

  PublicSubnet2:
    Description: A reference to the public subnet in the 2nd Availability Zone
    Type: String

Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  NatGateway1EIP:
    Type: AWS::EC2::EIP
    DependsOn: InternetGatewayAttachment
    Properties:
      Domain: vpc

  NatGateway2EIP:
    Type: AWS::EC2::EIP
    DependsOn: InternetGatewayAttachment
    Properties:
      Domain: vpc

  NatGateway1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGateway1EIP.AllocationId
      SubnetId: !Ref PublicSubnet1

  NatGateway2:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGateway2EIP.AllocationId
      SubnetId: !Ref PublicSubnet2


Outputs:
  InternetGateway:
    Description: A reference to the created InternetGateway
    Value: !Ref InternetGateway

  NatGateway1:
    Description: A reference to NatGateway1
    Value: !Ref NatGateway1

  NatGateway2:
    Description: A reference to NatGateway2
    Value: !Ref NatGateway2
